/*
Harmony Speech Engine API

API for the Harmony Speech Engine.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harmonyspeech

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

// DefaultAPIService DefaultAPI service
type DefaultAPIService service

type ApiConvertVoiceV1VoiceConvertPostRequest struct {
	ctx                    context.Context
	ApiService             *DefaultAPIService
	voiceConversionRequest *VoiceConversionRequest
	xApiKey                *string
	apiKey                 *string
}

func (r ApiConvertVoiceV1VoiceConvertPostRequest) VoiceConversionRequest(voiceConversionRequest VoiceConversionRequest) ApiConvertVoiceV1VoiceConvertPostRequest {
	r.voiceConversionRequest = &voiceConversionRequest
	return r
}

func (r ApiConvertVoiceV1VoiceConvertPostRequest) XApiKey(xApiKey string) ApiConvertVoiceV1VoiceConvertPostRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiConvertVoiceV1VoiceConvertPostRequest) ApiKey(apiKey string) ApiConvertVoiceV1VoiceConvertPostRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiConvertVoiceV1VoiceConvertPostRequest) Execute() (*VoiceConversionResponse, *http.Response, error) {
	return r.ApiService.ConvertVoiceV1VoiceConvertPostExecute(r)
}

/*
ConvertVoiceV1VoiceConvertPost Convert Voice

Convert the voice in an audio file or stream to a desired target voice.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiConvertVoiceV1VoiceConvertPostRequest
*/
func (a *DefaultAPIService) ConvertVoiceV1VoiceConvertPost(ctx context.Context) ApiConvertVoiceV1VoiceConvertPostRequest {
	return ApiConvertVoiceV1VoiceConvertPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return VoiceConversionResponse
func (a *DefaultAPIService) ConvertVoiceV1VoiceConvertPostExecute(r ApiConvertVoiceV1VoiceConvertPostRequest) (*VoiceConversionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *VoiceConversionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.ConvertVoiceV1VoiceConvertPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/voice/convert"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.voiceConversionRequest == nil {
		return localVarReturnValue, nil, reportError("voiceConversionRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	// body params
	localVarPostBody = r.voiceConversionRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateEmbeddingV1EmbedSpeakerPostRequest struct {
	ctx                 context.Context
	ApiService          *DefaultAPIService
	embedSpeakerRequest *EmbedSpeakerRequest
	xApiKey             *string
	apiKey              *string
}

func (r ApiCreateEmbeddingV1EmbedSpeakerPostRequest) EmbedSpeakerRequest(embedSpeakerRequest EmbedSpeakerRequest) ApiCreateEmbeddingV1EmbedSpeakerPostRequest {
	r.embedSpeakerRequest = &embedSpeakerRequest
	return r
}

func (r ApiCreateEmbeddingV1EmbedSpeakerPostRequest) XApiKey(xApiKey string) ApiCreateEmbeddingV1EmbedSpeakerPostRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiCreateEmbeddingV1EmbedSpeakerPostRequest) ApiKey(apiKey string) ApiCreateEmbeddingV1EmbedSpeakerPostRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiCreateEmbeddingV1EmbedSpeakerPostRequest) Execute() (*EmbedSpeakerResponse, *http.Response, error) {
	return r.ApiService.CreateEmbeddingV1EmbedSpeakerPostExecute(r)
}

/*
CreateEmbeddingV1EmbedSpeakerPost Create Embedding

Create a speaker embedding.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreateEmbeddingV1EmbedSpeakerPostRequest
*/
func (a *DefaultAPIService) CreateEmbeddingV1EmbedSpeakerPost(ctx context.Context) ApiCreateEmbeddingV1EmbedSpeakerPostRequest {
	return ApiCreateEmbeddingV1EmbedSpeakerPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return EmbedSpeakerResponse
func (a *DefaultAPIService) CreateEmbeddingV1EmbedSpeakerPostExecute(r ApiCreateEmbeddingV1EmbedSpeakerPostRequest) (*EmbedSpeakerResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *EmbedSpeakerResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.CreateEmbeddingV1EmbedSpeakerPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/embed/speaker"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.embedSpeakerRequest == nil {
		return localVarReturnValue, nil, reportError("embedSpeakerRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	// body params
	localVarPostBody = r.embedSpeakerRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateSpeechV1AudioSpeechPostRequest struct {
	ctx                 context.Context
	ApiService          *DefaultAPIService
	textToSpeechRequest *TextToSpeechRequest
	xApiKey             *string
	apiKey              *string
}

func (r ApiCreateSpeechV1AudioSpeechPostRequest) TextToSpeechRequest(textToSpeechRequest TextToSpeechRequest) ApiCreateSpeechV1AudioSpeechPostRequest {
	r.textToSpeechRequest = &textToSpeechRequest
	return r
}

func (r ApiCreateSpeechV1AudioSpeechPostRequest) XApiKey(xApiKey string) ApiCreateSpeechV1AudioSpeechPostRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiCreateSpeechV1AudioSpeechPostRequest) ApiKey(apiKey string) ApiCreateSpeechV1AudioSpeechPostRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiCreateSpeechV1AudioSpeechPostRequest) Execute() (*TextToSpeechResponse, *http.Response, error) {
	return r.ApiService.CreateSpeechV1AudioSpeechPostExecute(r)
}

/*
CreateSpeechV1AudioSpeechPost Create Speech

Generate speech Audio from text.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreateSpeechV1AudioSpeechPostRequest
*/
func (a *DefaultAPIService) CreateSpeechV1AudioSpeechPost(ctx context.Context) ApiCreateSpeechV1AudioSpeechPostRequest {
	return ApiCreateSpeechV1AudioSpeechPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return TextToSpeechResponse
func (a *DefaultAPIService) CreateSpeechV1AudioSpeechPostExecute(r ApiCreateSpeechV1AudioSpeechPostRequest) (*TextToSpeechResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *TextToSpeechResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.CreateSpeechV1AudioSpeechPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/audio/speech"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.textToSpeechRequest == nil {
		return localVarReturnValue, nil, reportError("textToSpeechRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	// body params
	localVarPostBody = r.textToSpeechRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateTranscriptionV1AudioTranscriptionsPostRequest struct {
	ctx                     context.Context
	ApiService              *DefaultAPIService
	speechTranscribeRequest *SpeechTranscribeRequest
	xApiKey                 *string
	apiKey                  *string
}

func (r ApiCreateTranscriptionV1AudioTranscriptionsPostRequest) SpeechTranscribeRequest(speechTranscribeRequest SpeechTranscribeRequest) ApiCreateTranscriptionV1AudioTranscriptionsPostRequest {
	r.speechTranscribeRequest = &speechTranscribeRequest
	return r
}

func (r ApiCreateTranscriptionV1AudioTranscriptionsPostRequest) XApiKey(xApiKey string) ApiCreateTranscriptionV1AudioTranscriptionsPostRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiCreateTranscriptionV1AudioTranscriptionsPostRequest) ApiKey(apiKey string) ApiCreateTranscriptionV1AudioTranscriptionsPostRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiCreateTranscriptionV1AudioTranscriptionsPostRequest) Execute() (*SpeechToTextResponse, *http.Response, error) {
	return r.ApiService.CreateTranscriptionV1AudioTranscriptionsPostExecute(r)
}

/*
CreateTranscriptionV1AudioTranscriptionsPost Create Transcription

Create a transcription from audio.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreateTranscriptionV1AudioTranscriptionsPostRequest
*/
func (a *DefaultAPIService) CreateTranscriptionV1AudioTranscriptionsPost(ctx context.Context) ApiCreateTranscriptionV1AudioTranscriptionsPostRequest {
	return ApiCreateTranscriptionV1AudioTranscriptionsPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return SpeechToTextResponse
func (a *DefaultAPIService) CreateTranscriptionV1AudioTranscriptionsPostExecute(r ApiCreateTranscriptionV1AudioTranscriptionsPostRequest) (*SpeechToTextResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *SpeechToTextResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.CreateTranscriptionV1AudioTranscriptionsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/audio/transcriptions"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.speechTranscribeRequest == nil {
		return localVarReturnValue, nil, reportError("speechTranscribeRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	// body params
	localVarPostBody = r.speechTranscribeRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateVadV1AudioVadPostRequest struct {
	ctx                        context.Context
	ApiService                 *DefaultAPIService
	detectVoiceActivityRequest *DetectVoiceActivityRequest
	xApiKey                    *string
	apiKey                     *string
}

func (r ApiCreateVadV1AudioVadPostRequest) DetectVoiceActivityRequest(detectVoiceActivityRequest DetectVoiceActivityRequest) ApiCreateVadV1AudioVadPostRequest {
	r.detectVoiceActivityRequest = &detectVoiceActivityRequest
	return r
}

func (r ApiCreateVadV1AudioVadPostRequest) XApiKey(xApiKey string) ApiCreateVadV1AudioVadPostRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiCreateVadV1AudioVadPostRequest) ApiKey(apiKey string) ApiCreateVadV1AudioVadPostRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiCreateVadV1AudioVadPostRequest) Execute() (*DetectVoiceActivityResponse, *http.Response, error) {
	return r.ApiService.CreateVadV1AudioVadPostExecute(r)
}

/*
CreateVadV1AudioVadPost Create Vad

Create a vad from audio.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreateVadV1AudioVadPostRequest
*/
func (a *DefaultAPIService) CreateVadV1AudioVadPost(ctx context.Context) ApiCreateVadV1AudioVadPostRequest {
	return ApiCreateVadV1AudioVadPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return DetectVoiceActivityResponse
func (a *DefaultAPIService) CreateVadV1AudioVadPostExecute(r ApiCreateVadV1AudioVadPostRequest) (*DetectVoiceActivityResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *DetectVoiceActivityResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.CreateVadV1AudioVadPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/audio/vad"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.detectVoiceActivityRequest == nil {
		return localVarReturnValue, nil, reportError("detectVoiceActivityRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	// body params
	localVarPostBody = r.detectVoiceActivityRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiHealthHealthGetRequest struct {
	ctx        context.Context
	ApiService *DefaultAPIService
}

func (r ApiHealthHealthGetRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.HealthHealthGetExecute(r)
}

/*
HealthHealthGet Health

Health check endpoint to verify the status of all engine serving objects.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiHealthHealthGetRequest
*/
func (a *DefaultAPIService) HealthHealthGet(ctx context.Context) ApiHealthHealthGetRequest {
	return ApiHealthHealthGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return map[string]interface{}
func (a *DefaultAPIService) HealthHealthGetExecute(r ApiHealthHealthGetRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.HealthHealthGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/health"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest struct {
	ctx        context.Context
	ApiService *DefaultAPIService
	xApiKey    *string
	apiKey     *string
}

func (r ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest) XApiKey(xApiKey string) ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest) ApiKey(apiKey string) ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest) Execute() (*ModelList, *http.Response, error) {
	return r.ApiService.ShowAvailableEmbeddingModelsV1EmbedModelsGetExecute(r)
}

/*
ShowAvailableEmbeddingModelsV1EmbedModelsGet Show Available Embedding Models

Show available embedding models.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest
*/
func (a *DefaultAPIService) ShowAvailableEmbeddingModelsV1EmbedModelsGet(ctx context.Context) ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest {
	return ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelList
func (a *DefaultAPIService) ShowAvailableEmbeddingModelsV1EmbedModelsGetExecute(r ApiShowAvailableEmbeddingModelsV1EmbedModelsGetRequest) (*ModelList, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.ShowAvailableEmbeddingModelsV1EmbedModelsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/embed/models"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest struct {
	ctx        context.Context
	ApiService *DefaultAPIService
	xApiKey    *string
	apiKey     *string
}

func (r ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest) XApiKey(xApiKey string) ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest) ApiKey(apiKey string) ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest) Execute() (*ModelList, *http.Response, error) {
	return r.ApiService.ShowAvailableSpeechModelsV1AudioSpeechModelsGetExecute(r)
}

/*
ShowAvailableSpeechModelsV1AudioSpeechModelsGet Show Available Speech Models

Show available speech models.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest
*/
func (a *DefaultAPIService) ShowAvailableSpeechModelsV1AudioSpeechModelsGet(ctx context.Context) ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest {
	return ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelList
func (a *DefaultAPIService) ShowAvailableSpeechModelsV1AudioSpeechModelsGetExecute(r ApiShowAvailableSpeechModelsV1AudioSpeechModelsGetRequest) (*ModelList, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.ShowAvailableSpeechModelsV1AudioSpeechModelsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/audio/speech/models"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest struct {
	ctx        context.Context
	ApiService *DefaultAPIService
	xApiKey    *string
	apiKey     *string
}

func (r ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest) XApiKey(xApiKey string) ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest) ApiKey(apiKey string) ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest) Execute() (*ModelList, *http.Response, error) {
	return r.ApiService.ShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetExecute(r)
}

/*
ShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGet Show Available Transcription Models

Show available transcription models.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest
*/
func (a *DefaultAPIService) ShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGet(ctx context.Context) ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest {
	return ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelList
func (a *DefaultAPIService) ShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetExecute(r ApiShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGetRequest) (*ModelList, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.ShowAvailableTranscriptionModelsV1AudioTranscriptionsModelsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/audio/transcriptions/models"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiShowAvailableVadModelsV1AudioVadModelsGetRequest struct {
	ctx        context.Context
	ApiService *DefaultAPIService
	xApiKey    *string
	apiKey     *string
}

func (r ApiShowAvailableVadModelsV1AudioVadModelsGetRequest) XApiKey(xApiKey string) ApiShowAvailableVadModelsV1AudioVadModelsGetRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiShowAvailableVadModelsV1AudioVadModelsGetRequest) ApiKey(apiKey string) ApiShowAvailableVadModelsV1AudioVadModelsGetRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiShowAvailableVadModelsV1AudioVadModelsGetRequest) Execute() (*ModelList, *http.Response, error) {
	return r.ApiService.ShowAvailableVadModelsV1AudioVadModelsGetExecute(r)
}

/*
ShowAvailableVadModelsV1AudioVadModelsGet Show Available Vad Models

Show available vad models.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiShowAvailableVadModelsV1AudioVadModelsGetRequest
*/
func (a *DefaultAPIService) ShowAvailableVadModelsV1AudioVadModelsGet(ctx context.Context) ApiShowAvailableVadModelsV1AudioVadModelsGetRequest {
	return ApiShowAvailableVadModelsV1AudioVadModelsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ModelList
func (a *DefaultAPIService) ShowAvailableVadModelsV1AudioVadModelsGetExecute(r ApiShowAvailableVadModelsV1AudioVadModelsGetRequest) (*ModelList, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ModelList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.ShowAvailableVadModelsV1AudioVadModelsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/audio/vad/models"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest struct {
	ctx        context.Context
	ApiService *DefaultAPIService
	xApiKey    *string
	apiKey     *string
}

func (r ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest) XApiKey(xApiKey string) ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest) ApiKey(apiKey string) ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.ShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetExecute(r)
}

/*
ShowAvailableVoiceConversionModelsV1VoiceConvertModelsGet Show Available Voice Conversion Models

Show available voice conversion models.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest
*/
func (a *DefaultAPIService) ShowAvailableVoiceConversionModelsV1VoiceConvertModelsGet(ctx context.Context) ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest {
	return ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return interface{}
func (a *DefaultAPIService) ShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetExecute(r ApiShowAvailableVoiceConversionModelsV1VoiceConvertModelsGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.ShowAvailableVoiceConversionModelsV1VoiceConvertModelsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/voice/convert/models"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiShowVersionVersionGetRequest struct {
	ctx        context.Context
	ApiService *DefaultAPIService
	xApiKey    *string
	apiKey     *string
}

func (r ApiShowVersionVersionGetRequest) XApiKey(xApiKey string) ApiShowVersionVersionGetRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiShowVersionVersionGetRequest) ApiKey(apiKey string) ApiShowVersionVersionGetRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiShowVersionVersionGetRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.ShowVersionVersionGetExecute(r)
}

/*
ShowVersionVersionGet Show Version

Fetch the Harmony Speech Engine version.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiShowVersionVersionGetRequest
*/
func (a *DefaultAPIService) ShowVersionVersionGet(ctx context.Context) ApiShowVersionVersionGetRequest {
	return ApiShowVersionVersionGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return map[string]interface{}
func (a *DefaultAPIService) ShowVersionVersionGetExecute(r ApiShowVersionVersionGetRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultAPIService.ShowVersionVersionGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/version"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "simple", "")
	}
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "Api-Key", r.apiKey, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
