/*
Harmony Speech Engine API

API for the Harmony Speech Engine.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package harmonyspeech

import (
	"encoding/json"
)

// checks if the DetectVoiceActivityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetectVoiceActivityRequest{}

// DetectVoiceActivityRequest DetectVoiceActivityRequest Used to check for human speech in a provided audio file Depending on model selection, the caller may need to provide additional params.
type DetectVoiceActivityRequest struct {
	// the name of the model
	Model *string `json:"model,omitempty"`
	// Binary audio data of the reference speaker for synthesizing the text, encoded in base64
	InputAudio           *string      `json:"input_audio,omitempty"`
	GetTimestamps        NullableBool `json:"get_timestamps,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DetectVoiceActivityRequest DetectVoiceActivityRequest

// NewDetectVoiceActivityRequest instantiates a new DetectVoiceActivityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetectVoiceActivityRequest() *DetectVoiceActivityRequest {
	this := DetectVoiceActivityRequest{}
	var model string = ""
	this.Model = &model
	return &this
}

// NewDetectVoiceActivityRequestWithDefaults instantiates a new DetectVoiceActivityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetectVoiceActivityRequestWithDefaults() *DetectVoiceActivityRequest {
	this := DetectVoiceActivityRequest{}
	var model string = ""
	this.Model = &model
	return &this
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *DetectVoiceActivityRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetectVoiceActivityRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *DetectVoiceActivityRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *DetectVoiceActivityRequest) SetModel(v string) {
	o.Model = &v
}

// GetInputAudio returns the InputAudio field value if set, zero value otherwise.
func (o *DetectVoiceActivityRequest) GetInputAudio() string {
	if o == nil || IsNil(o.InputAudio) {
		var ret string
		return ret
	}
	return *o.InputAudio
}

// GetInputAudioOk returns a tuple with the InputAudio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetectVoiceActivityRequest) GetInputAudioOk() (*string, bool) {
	if o == nil || IsNil(o.InputAudio) {
		return nil, false
	}
	return o.InputAudio, true
}

// HasInputAudio returns a boolean if a field has been set.
func (o *DetectVoiceActivityRequest) HasInputAudio() bool {
	if o != nil && !IsNil(o.InputAudio) {
		return true
	}

	return false
}

// SetInputAudio gets a reference to the given string and assigns it to the InputAudio field.
func (o *DetectVoiceActivityRequest) SetInputAudio(v string) {
	o.InputAudio = &v
}

// GetGetTimestamps returns the GetTimestamps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DetectVoiceActivityRequest) GetGetTimestamps() bool {
	if o == nil || IsNil(o.GetTimestamps.Get()) {
		var ret bool
		return ret
	}
	return *o.GetTimestamps.Get()
}

// GetGetTimestampsOk returns a tuple with the GetTimestamps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DetectVoiceActivityRequest) GetGetTimestampsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.GetTimestamps.Get(), o.GetTimestamps.IsSet()
}

// HasGetTimestamps returns a boolean if a field has been set.
func (o *DetectVoiceActivityRequest) HasGetTimestamps() bool {
	if o != nil && o.GetTimestamps.IsSet() {
		return true
	}

	return false
}

// SetGetTimestamps gets a reference to the given NullableBool and assigns it to the GetTimestamps field.
func (o *DetectVoiceActivityRequest) SetGetTimestamps(v bool) {
	o.GetTimestamps.Set(&v)
}

// SetGetTimestampsNil sets the value for GetTimestamps to be an explicit nil
func (o *DetectVoiceActivityRequest) SetGetTimestampsNil() {
	o.GetTimestamps.Set(nil)
}

// UnsetGetTimestamps ensures that no value is present for GetTimestamps, not even an explicit nil
func (o *DetectVoiceActivityRequest) UnsetGetTimestamps() {
	o.GetTimestamps.Unset()
}

func (o DetectVoiceActivityRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetectVoiceActivityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.InputAudio) {
		toSerialize["input_audio"] = o.InputAudio
	}
	if o.GetTimestamps.IsSet() {
		toSerialize["get_timestamps"] = o.GetTimestamps.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DetectVoiceActivityRequest) UnmarshalJSON(data []byte) (err error) {
	varDetectVoiceActivityRequest := _DetectVoiceActivityRequest{}

	err = json.Unmarshal(data, &varDetectVoiceActivityRequest)

	if err != nil {
		return err
	}

	*o = DetectVoiceActivityRequest(varDetectVoiceActivityRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "model")
		delete(additionalProperties, "input_audio")
		delete(additionalProperties, "get_timestamps")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDetectVoiceActivityRequest struct {
	value *DetectVoiceActivityRequest
	isSet bool
}

func (v NullableDetectVoiceActivityRequest) Get() *DetectVoiceActivityRequest {
	return v.value
}

func (v *NullableDetectVoiceActivityRequest) Set(val *DetectVoiceActivityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDetectVoiceActivityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDetectVoiceActivityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetectVoiceActivityRequest(val *DetectVoiceActivityRequest) *NullableDetectVoiceActivityRequest {
	return &NullableDetectVoiceActivityRequest{value: val, isSet: true}
}

func (v NullableDetectVoiceActivityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetectVoiceActivityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
